hostname="freebsd-box"
create_args_wlan0="country RO regdomain ETSI" # Adjust based on your region
wlans_iwlwifi0="wlan0"
ifconfig_wlan0="WPA SYNCDHCP"
ifconfig_wlan0_ipv6="inet6 accept_rtadv"
background_dhclient="YES"
ipv6_activate_all_interfaces="YES"
rtsold_enable="YES"
rtsold_flags="-a"
# This prevents the boot from waiting for a default route on ipv6
defaultroute_delay="0"
ntpd_enable="YES"
powerd_enable="YES"
moused_nondefault_enable="NO"
# Set dumpdev to "AUTO" to enable crash dumps, "NO" to disable
dumpdev="NO"
zfs_enable="YES"
seatd_enable="YES"
dbus_enable="YES"
kld_list="i915kms fusefs"
uhidd_flags="-k"
ifconfig_em0="DHCP"
devfs_system_ruleset="localruleset"
